bases:
- ../../base
configMapGenerator:
- name: demo-configmap
  behavior: merge
  files:
    - application.properties
  literals:
    - foo=bar
  env: staging.env
namePrefix: staging-
commonLabels:
  env: staging
